### PR TITLE
Use 'CopyConst' to Visitors over both const and non-const IR

### PR DESCRIPTION
**Pull request by Cypher1**
This draft is based on https://github.com/google-research/raksha/pull/598
I'm sending it out as a preview of future work we could do.

Needs:
- Tests for non-const IR traversal (i.e. traversal while performing mutations)
- Static checks for CopyConst and SelectType (there's tests but these are pretty limited).
- Comments

### CODE REVIEW

**Comment by Cypher1** [comment]
@markww @aferr @bgogul FYI. Not sure we need this but thought I'd put it up for reference.

**Comment by Cypher1** [comment]
Thanks @markww I think I have to close this to do that. Brb

**Comment by markww** [comment]
J, you don't have to close the PR to change the branch that it merges into. If you press the "Edit" button on the PR, you should get a dropdown with all of the active branches and you can just select a different one. Sorry, I didn't intend for you to have to wrestle with GitHub this much.

**Comment by Cypher1** [comment]
Thanks Mark,
Yeah, I thought that'd work but for me it wasn't showing up. It was no big
deal to fix.

J Pratt | (they/them) | Arcs Syd | ***@***.***

**Pull request closed without merging**
