### PR TITLE
Draft creating types from Manifest protos

### PR DESCRIPTION
**Pull request by markww**

### CODE REVIEW

**Comment by markww** [comment]
Depends on #86 , do not merge before that PR.

**Comment by bgogul** [comment]
It is still marked as draft. Is it ready for review?

**Comment by markww** [comment]
This PR is not, but #86 is.

**Comment by markww** [comment]
OK, this is now ready for review, with the caveat that until #86 is merged into main, it will probably be harder to reason about which parts belong to which PR.

**Review by bgogul — APPROVED** [review]

**Pull request merged**
