### PR TITLE
Replace claimHasTag relation with saysHasTag. 

### PR DESCRIPTION
**Pull request by bgogul**
These are equivalent relations. `saysHasTag` is more aligned with authorization logic claims and we should just use that going forward.

### CODE REVIEW

**Comment by aferr** [comment]
I think you should now be able to get rid of `claimHasTag` in [authorization_logic.dl](https://github.com/google-research/raksha/blob/main/src/analysis/souffle/authorization_logic.dl). You might also want to look around for other uses of `claimHasTag` in rules in `../analyis/souffle/*` to see if you can simplify them away now as well.

**Review by aferr — CHANGES_REQUESTED** [review]
Can you remove `claimHasTag` from `authorizaiton_logic.dl` now? Maybe double check for other uses in `analysis/souffle` as well? 

(sorry for the duplicate comment. this was just bad use of github on my part).

**Review by markww — APPROVED** [review]
LGTM

**Comment by bgogul** [comment]
> Can you remove `claimHasTag` from `authorizaiton_logic.dl` now? Maybe double check for other uses in `analysis/souffle` as well?
> 
> (sorry for the duplicate comment. this was just bad use of github on my part).

@aferr I don't see any references to claimHasTag in `authorization_logic.dl`. I searched all the code base too. Am I missing something?

**Review by aferr — APPROVED** [review]
@bgogul Actually you did get all the uses of claimHasTag (including the one in `authorization_logic.dl`). I must have hallucinated that it was missed.

**Pull request merged**
