### PR TITLE
Add souffle as a third_party library.

### PR DESCRIPTION
**Pull request by bgogul**
Setting up souffle as a third_party repo so that it can be used in the project.

### CODE REVIEW

**Review by aferr — APPROVED** [review]
Looks good! One question: Conrad mentioned in another PR that we should have copyright info at the top of every file. Do we need that for these as well?

**Comment by aferr** [comment]
Err, I see now that you wrote WIP in the title. Let me know if you want me to undo the approval and wait.

**Comment by bgogul** [comment]
> Looks good! One question: Conrad mentioned in another PR that we should have copyright info at the top of every file. Do we need that for these as well?

Yes, we will need to add copyright info to all files. I added them right now. I also added an example exercising Souffle's C++ interface.

**Comment by bgogul** [comment]
@markww just FYI.

**Pull request merged**
