### PR TITLE
Fix Bazel canonical build warnings for two external deps.

### PR DESCRIPTION
**Pull request by shaper**
Add sha256 for `hedron_compile_commands` and `com_google_googletest`.

### CODE REVIEW

**Comment by shaper** [comment]
CI is failing though it works locally. Attempting to view gives me permission-access error for `raksha-ci`, maybe it's just not letting me run CI due to permissions?

**Comment by shaper** [comment]
Fixed buildifier error, PTAL. Still need CI access from whomever can grant it, though.

**Comment by markww** [comment]
@bgogul , what do we need to do to grant @shaper CI access?

**Review by markww — APPROVED** [review]
This PR looks good to me. One issue though: you've submitted this PR from an external fork rather than from a dev branch within google-research/raksha. I don't know whether that will work for most PRs with our Copybara setup. Fortunately, this PR has no internal footprint, so I think there shouldn't be an issue with you just merging it.

**Comment by bgogul** [comment]
> One issue though: you've submitted this PR from an external fork rather than from a dev branch within google-research/raksha

It does not matter. Copybara gets triggered if google/main is the target of the merge. It doesn't matter what the source is. We have been creating branches on google-research/raksha itself mainly to facilitate dependent PRs. If you don't need it, you can totally create branches on a fork.

**Pull request merged**
